name: "Project Check"
description: ""

inputs:
    exec:
        description: "The name of the action to execute"    
        required: true
    before:
        description: "The SHA of the previous commit -> see: {{ github.event.before }}"
        required: true
    after:
        description: "The SHA of the new commit -> see: {{ github.sha }}"
        required: true
    repository:
        description: "The name of the owner & repository -> see: {{ github.repository }}"
        required: true
    token:
        description: "The token of the github action -> see: {{ secrets.GITHUB_TOKEN }}"
        required: true
    slack:
        description: "The oauth token of the bot to send the slack message from"
        required: true
    run:
        description: "The run id of the github action -> see {{ github.run_id }}"
        required: true
    
runs:
    using: "docker"
    image: "Dockerfile"
    env:
        RUN_SCRIPT: ${{ inputs.exec }}
        SHA_BEFORE: ${{ inputs.before }}
        SHA_AFTER: ${{ inputs.after }}
        REPO_NAME: ${{ inputs.repository }}
        REPO_TOKEN: ${{ inputs.token }}
        SLACK_OAUTH: ${{ inputs.slack }}
        GIT_RUN: ${{ inputs.run }}
        
        
branding:
    icon: "slack"  
    color: "orange"