name: "Project Check"
description: ""

inputs:
    run:
        description: "The name of the action to execute"    
        required: true

runs:
      using: "docker"
      image: "Dockerfile"
      env:
          RUN_SCRIPT: ${{ inputs.run }}
        
branding:
    icon: "slack"  
    color: "orange"