# name: Auto Release
# 
# on: [push]
# 
# jobs:
#   build:
#     name: Create Release
#     runs-on: ubuntu-latest
#     steps:
# 
#       - name: Checkout
#         id: checkout
#         uses: actions/checkout@v2
# 
#       - name: Release
#         id: release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag_name: v1
#           release_name: Initial Release
#           body: Autoreleased by actions
#           prerelease: true