name: Demo

on: push
    
jobs:
    
    first_job:
        
        name: First Job
        runs-on: ubuntu-latest
        
        steps:
            
          - name: First Step
            id: first_step
            run: echo "::set-output name=fruit::strawberry"
            
          - name: Second Step
            id: second_step
            run: echo ${{ steps.first_step.outputs.fruit }}
            