name: Demo

on: push
    
jobs:
    
    first_job:
        
        name: First Job
        runs-on: ubuntu-latest
        
        steps:
            
          - name: First Step
            id: first_step
            run: echo "::set-output name=fruit::strawberry"
            
          - name: Second Step
            id: second_step
            run: echo test
            
          - name: Sleep for 15 seconds
            uses: jakejarvis/wait-action@master
            with:
                time: '15s'
                
    second_job: 
        
        name: Second Job
        needs: first_job
        runs-on: ubuntu-latest
        
        steps:
    
          - name: First Step
            id: first_step
            run: echo "Hello"
        
            