name: Demo

on: push
    
jobs:
    
    first_job:
        
        name: First Job
        runs-on: ubuntu-latest
        
        steps:
            
          - name: First Step
            id: first_step
            run: echo "Hello world"
            